name: Compile & Deploy to Polygon Amoy (Windows)

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: windows-latest
    env:
      NODE_OPTIONS: "--max_old_space_size=4096"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          Write-Host "Installing dependencies..."
          npm install --legacy-peer-deps
          Write-Host "Installing Hardhat..."
          npm install --save-dev hardhat@2.17.3 @nomiclabs/hardhat-ethers@2.2.3 ethers@5.8.0
        shell: pwsh

      - name: Verify installation
        run: |
          Write-Host "Node version:"
          node --version
          Write-Host "NPM version:"
          npm --version
          Write-Host "Hardhat version:"
          npx hardhat --version
        shell: pwsh

      - name: Compile contracts
        run: |
          Write-Host "Compiling contracts..."
          npx hardhat compile
        shell: pwsh

      - name: Deploy contracts to Amoy
        env:
          POLYGON_RPC_URL: ${{ secrets.POLYGON_AMOY_RPC }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: |
          Write-Host "Creating .env file..."
          @"
POLYGON_RPC_URL=$env:POLYGON_RPC_URL
PRIVATE_KEY=$env:PRIVATE_KEY
"@ | Out-File -Encoding utf8 .env

          Write-Host "Deploying contracts..."
          npx hardhat run scripts/deploy-with-output.js --network amoy
        shell: pwsh

      - name: Show results
        if: success()
        run: |
          if (Test-Path "deployed-addresses.json") {
            Write-Host "✅ Deployment successful!"
            Write-Host "Contract addresses:"
            Get-Content "deployed-addresses.json" | Write-Host
          } else {
            Write-Host "❌ No deployed-addresses.json found"
          }
        shell: pwsh

      - name: Upload deployed addresses artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: deployed-addresses
          path: deployed-addresses.json